---
# akoi - binary version control system
# https://github.com/suzuki-shunsuke/akoi
bin_path: ".akoi/pkgs/{{.Name}}/{{.Version}}/{{.Name}}"
link_path: ".akoi/bin/{{.Name}}"
packages:
  github-comment:
    url: 'https://github.com/suzuki-shunsuke/{{.Name}}/releases/download/{{.Version}}/{{.Name}}_{{trimPrefix "v" .Version}}_{{.OS}}_{{.Arch}}.tar.gz'
    version: v2.0.1 # renovate: depName=suzuki-shunsuke/github-comment
    files:
    - name: github-comment
      archive: "{{.Name}}"
