name: dummy
on:
  pull_request:
    branches: [dummy]
  push:
    branches: [dummy]
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: suzuki-shunsuke/tfaction/setup@2facef52f4c67aa7e6e477b28650d4be2c64cbc7 # v0.5.20
