---
name: pinact

on: pull_request

env:
  AQUA_LOG_COLOR: always

permissions: {}

jobs:
  pinact:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    permissions:
      contents: read # To checkout private repository
    steps:
      - uses: actions/checkout@v3
