---
name: pinact

on: pull_request

env:
  AQUA_LOG_COLOR: always

permissions: {}

jobs:
  pinact:
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout private repository
    steps:
      - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5 # main
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
