name: test
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.0.0
      - name: success
        run: "true"
