---
name: pinact

on: pull_request

env:
  AQUA_LOG_COLOR: always

permissions: {}

jobs:
  pinact:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    permissions:
      contents: read # To checkout private repository
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
