name: test
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: "false"
      - uses: aquaproj/aqua-installer@feat/run-aqua-install
        with:
          aqua_version: v0.8.7 # use old version for test
