name: test
on:
  pull_request:
    branches: [dummy]
  push:
    branches: [dummy]
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: "1.19.0"
          cache: true
