name: test
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: success
        run: "true"
