---
name: pinact

on: pull_request

env:
  AQUA_LOG_COLOR: always

permissions: {}

jobs:
  pinact:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    permissions:
      contents: read # To checkout private repository
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - uses: actions/cache@387e18722e6ff315b24a3b8b071feddd27b7bf7e # v3.4.2
