---
name: pinact

on: pull_request

env:
  AQUA_LOG_COLOR: always

permissions: {}

jobs:
  pinact:
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout private repository
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # main
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
